---
framework: mocha
licenseTier: xsmall
blocklist:
   - "./test/options.spec.ts##options##cwd##should use process.cwd() if nothing is provided"
   - "./test/target.spec.ts##Targets##new test for BL oK"
postMerge:
  pattern:
    - "./test/*.spec.ts"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/*.spec.ts"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 2.2
