---
framework: mocha
tier: xsmall
blocklist:
   - "./test/target.spec.ts##Targets##new test for BL oK" 
postMerge:
  pattern: 
    - "./test/**/*.spec.ts"
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
postRun:
     command:
        - node --version
version: 2.2
