---
framework: mocha
tier: small

postMerge:
  pattern: 
    - "./test/**/*.something-wtf.spec.ts"
preMerge:
  pattern:
    - "./test/**/*.something-wtf.spec.ts"
preRun:
     command:
        - npm ci
postRun:
     command:
        - node --version
version: 1.0.3
parallelism : 4
